config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  devise_for :users, controllers: {
    registrations: 'user/registrations',
    omniauth_callbacks: 'user/omniauth_callbacks'
  }

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :events, only: [:index, :show]
      resources :locations, only: [:show]
    end
  end
  get "/api/v1/events/category/:category",
    to: "api/v1/events#category", defaults: { format: :json }
  get "/api/v1/events/location/:location",
    to: "api/v1/events#location", defaults: { format: :json }
  get "/api/v1/events/postalcode/:postalcode",
    to: "api/v1/events#postalcode", defaults: { format: :json }

  resources :events , only: [:index, :show]
  get 'pages/about'
  get 'pages/map'
  get 'pages/map_with_location/:location', to: 'pages#map_with_location'
  get 'pages/map_with_category/:category', to: 'pages#map_with_category'
  get '/events/category/:category', to: 'events#category'
  get '/events/location/:location', to: 'events#location'
  get '/events/postalcode/:postalcode', to: 'events#postalcode', as: :events_postalcode
  get '/events/district/:district', to: 'events#district'
  get '/unsubscribes/:token', to: 'unsubscribes#show'

  mount Sidekiq::Web => '/sidekiq'

  get '*unmatched_route', to: 'application#route_not_found'
end

app/models/event.rb
class Event < ApplicationRecord
  enum category: [ :earthquake, :flood, :rainfall ]
  belongs_to :location
  has_many :users, through: :location
  after_create :notify_users
  paginates_per 20

  default_scope               -> { order('start_at DESC') }
  scope :this_weeks,          -> { where('start_at >= ?', 1.week.ago) }
  scope :most_recent,         -> (limit) { limit(limit) }
  scope :available_locations, -> { joins(:location).pluck(:province).uniq }
  scope :by_category,         -> (category) { where(category: category) }
  scope :by_location,         -> (location) do
    joins(:location).where(locations: { province: location })
  end
  scope :by_postalcode,       -> (postal_code) do
    joins(:location).where(locations: { postal_code: postal_code })
  end
  scope :by_district,         -> (district) do
    joins(:location).where(locations: { district: district })
  end

  private

  def notify_users
    users.reject(&:unsubscribed_from_emails).each do |user|
      NotificationMailer.event_warning(user, self).deliver_later
    end
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController
  before_action :set_headers

  def index
    @events = Event.this_weeks.page(params[:page])
    render :index, status: :ok
  end

  def show
    @event = Event.find(params[:id])
    render :show, status: :ok
  end

  def category
    category =
      case params[:category]
      when 'แผ่นดินไหว' then 'earthquake'
      when 'น้ำท่วม'    then 'flood'
      when 'ฝนตกหนัก'  then 'rainfall'
      when 'ฝนตก'     then 'rainfall'
      else params[:category]
      end

    @events = Event.by_category(category).this_weeks.page(params[:page])
    render :index, status: :ok
  end

  def location
    @events = Event.by_location(params[:location]).this_weeks.page(params[:page])
    render :index, status: :ok
  end

  def postalcode
    @events = Event.by_postalcode(params[:postalcode]).
                this_weeks.
                page(params[:page])
    render :index, status: :ok
  end

  private

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.this_weeks.page(params[:page])
    set_locations
  end

  def show
    if @event = Event.find_by(id: params[:id])
      @hospitals_nearby = Hospital.near_by(@event.location.postal_code.to_i)
    end
  end

  def category
    @events = Event.by_category(params[:category]).this_weeks.page(params[:page])
    set_locations
    render :index
  end

  def location
    @events = Event.by_location(params[:location]).this_weeks.page(params[:page])
    set_locations
    render :index
  end

  def postalcode
    @events = Event.by_postalcode(params[:postalcode]).this_weeks.page(params[:page])
    @location = Location.find_by(postal_code: params[:postalcode])
    set_locations
    render :index
  end

  def district
    @location = Location.find_by(district: params[:district])
    @location = Location.new.similar_district(params[:district]) if @location.nil?
    @events = Event.by_district(@location.district).this_weeks.page(params[:page])
    set_locations
    render :index
  end

  private

  def set_locations
    @event_categories = Event.categories.keys
    @event_provinces = Event.available_locations
  end
end

app/views/events/_default_preparation.html.erb
<div class="row">
  <div class="col-md-1">
    <%= icon('map-o') %>
  </div>
  <div class="col-md-11">
    <h4><strong>วางแผนสิ่งที่ควรปฏิบัติ</strong></h4>
    <p>
      วางแผนที่จะติดต่อสื่อสารถึง เพื่อน ญาติพี่น้อง หรือครอบครัว เผื่อไว้หลายๆ รูปแบบ
      หากโทรศัพท์บ้านหรือโทรศัพท์มือถือใช้การไม่ได้ ก็อาจใช้อีเมลแทน
    </p>
  </div>
</div>
<div class="row">
  <div class="col-md-1">
    <%= icon('warning') %>
  </div>
  <div class="col-md-11">
    <h4><strong>เตรียมรวบรวมสิ่งของเครื่องใช้ที่จำเป็น</strong></h4>
    <p>
      เอกสารสำคัญประจำตัว เช่น หนังสือเดินทาง ใบขับขี่ บัตรประกันสุขภาพ และอื่นๆ
      ควรเก็บไว้ในถุงพลาสติกหรือแฟ้มที่กันน้ำได้ น้ำสะอาดสำหรับใช้ดื่ม อาหารแห้ง สำเร็จรูป
      เครื่องกระป๋อง ให้เพียงพอ อย่างน้อย 3 วัน
    </p>
  </div>
</div>
<div class="row">
  <div class="col-md-1">
    <%= icon('support') %>
  </div>
  <div class="col-md-11">
    <h4><strong>ติดตามข่าวสารในเขตพื้นที่ที่พักอาศัย</strong></h4>
    <p>
      ควรรับฟังข่าวสาร ประกาศเตือน จากทางสื่อวิทยุ โทรทัศน์ อินเตอร์เน็ท เป็นประจำทุกวัน
      พร้อมที่จะปรับใช้แผนที่เตรียมไว้ เข้ากับสถานะการณ์ที่เกิดขึ้นได้อย่างเหมาะสม
    </p>
  </div>
</div>

app/views/events/_earthquake_preparation.html.erb
<div class="row">
  <div class="col-md-1">
    <%= icon('map-o') %>
  </div>
  <div class="col-md-11">
    <h4><strong>ก่อนแผ่นดินไหว</strong></h4>
    <ul>
      <li>สมัครและรอรับรับข่าวเตือนภัยจากเรา</li>
      <li>ดูข้อมูลน้ำท่วมในเขตของคุณ</li>
      <li>ฝึกเคลื่อนย้ายสู่สถานที่ปลอดภัยเช่น ใต้โต๊ะ หรือที่โล่งแจ้ง</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-1">
    <%= icon('warning') %>
  </div>
  <div class="col-md-11">
    <h4><strong>ขณะแผ่นดินไหว (หากอยู่ในอาคาร)</strong></h4>
    <ul>
      <li>เคลื่อนย้ายสู่สถานที่ปลอดภัยเช่น ใต้โต๊ะ</li>
      <li>หลีกเลี่ยงการวิ่งออกจากอาคาร</li>
      <li>หลีกเลี่ยงการอยู่ใกล้กระจก ผนัง และสิ่งของที่อาจล้มทับ</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-1">
    <%= icon('support') %>
  </div>
  <div class="col-md-11">
    <h4><strong>หลังแผ่นดินไหว</strong></h4>
    <ul>
      <li>เคลื่อนย้ายสู่ที่โล่ง ห่างจากอาคาร</li>
      <li>หากคุณถูกกดทับ ไม่สามารถเคลื่อนไหว พยายามหาสิ่งของ เคาะให้เกิดเสียง เพื่อขอความช่วยเหลือ</li>
      <li>เตรียมพร้อมหากเกิดแผ่นดินไหวอีกครั้ง</li>
    </ul>
  </div>
</div>

app/views/events/_event.html.erb
<tr>
  <td><%= link_to event.title, event_path(event) %></td>
  <td><%= t("categories.#{event.category}") %></td>
  <td><%= event.latitude %></td>
  <td><%= event.longitude %></td>
  <td><%= external_link_to event.source_name, truncate_url(event.source_url) %></td>
  <td>
    <%= link_to "#{event.location.district}, #{event.location.province}",
      events_postalcode_path(event.location.postal_code) %>
  </td>
  <td><%= event.start_at.strftime("%-d/%-m/%y: %H:%M") %></td>
</tr>

app/views/events/_flood_preparation.html.erb
<div class="row">
  <div class="col-md-1">
    <%= icon('map-o') %>
  </div>
  <div class="col-md-11">
    <h4><strong>ก่อนน้ำท่วม</strong></h4>
    <ul>
      <li>สมัครและรอรับรับข่าวเตือนภัยจากเรา</li>
      <li>ดูข้อมูลน้ำท่วมในเขตของคุณ</li>
      <li>ปิดน้ำ, ไฟฟ้า และ แก๊ส ภายในบ้าน</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-1">
    <%= icon('warning') %>
  </div>
  <div class="col-md-11">
    <h4><strong>ขณะน้ำท่วม</strong></h4>
    <ul>
      <li>โทรขอความช่วยเหลือไปยัง 1111 กด 5 <%= external_link_to "(ศปภ.)", "http://www.dgr.go.th/flood/" %></li>
      <li>หลีกเลี่ยงการเดินทางในจุดน้ำท่วม</li>
      <li>ให้ความช่วยเหลือ หรือขอความช่วยเหลือจากเพื่อนบ้าน</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-1">
    <%= icon('support') %>
  </div>
  <div class="col-md-11">
    <h4><strong>หลังน้ำท่วม</strong></h4>
    <ul>
      <li>เลี่ยงการใช้แก๊ส, ไฟฟ้า ก่อนตรวจสอบจากช่าง</li>
      <li>เลี่ยงอาหารที่สัมผัสน้ำท่วม</li>
      <li>โทรสอบถามการประปา ก่อนการใช้น้ำ</li>
    </ul>
  </div>
</div>

app/views/events/_infowindow.html.erb
<%= link_to event_title, event_url %>
<p><%= event_date %></p>

app/views/events/index.html.erb
<% provide :title, "ข้อมูลเตือนภัย" %>

<div class="container">
  <h1>ข้อมูลเตือนภัย</h1>
  <% if @location.present? %>
    <h4>พื้นที่: <%= @location.district %>, <%= @location.province %></h4>
  <% end %>
  <br />
  <div class="dropdown category-select pull-left">
    <button type="button" class="btn btn-default btn-right dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      ประเภท <span class="caret"></span>
    </button>

    <ul id="sidebar_container" class="dropdown-menu">
      <% @event_categories.each do |category| %>
      <li><%= link_to t("categories.#{category}"), "/events/category/#{category}" %></li>
      <% end %>
      <li role="separator" class="divider"></li>
      <li><%= link_to "ทั้งหมด", events_path %></li>
    </ul>
  </div>

  <div class="dropdown category-select pull-left">
    <button type="button" class="btn btn-default btn-right dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      จังหวัด <span class="caret"></span>
    </button>
    <ul id="sidebar_container" class="dropdown-menu">
      <% @event_provinces.each do |province| %>
      <li><%= link_to t("locations.#{province}"), "/events/location/#{province}" %></li>
      <% end %>
      <li role="separator" class="divider"></li>
      <li><%= link_to "ทั้งหมด", events_path %></li>
    </ul>
  </div>

  <br /><br />
  <hr/>
  <% if @events.present? %>
    <div class="table-responsive">
      <table class="table table-condensed table-striped table-hover">
        <thead>
          <tr>
            <th>ชื่อเหตุการณ์</th>
            <th>ประเภท</th>
            <th>ละติจูด</th>
            <th>ลองติจูด</th>
            <th>แหล่งข้อมูล</th>
            <th>ตำแหน่ง</th>
            <th>วัน-เวลา</th>
          </tr>
        </thead>
        <tbody>
          <%= render :partial => "event", :collection => @events %>
        </tbody>
      </table>
    </div>
    <%= paginate @events %>
  <% else %>
    ไม่มีข้อมูลเตือนภัยใน 7 วันที่ผ่านมา
  <% end %>
</div>

app/views/events/show.html.erb
<% provide :title, (@event.present? ? @event.title : "ไม่พบข้อมูล" ) %>

<% if @event.present? %>
  <div class="container">
    <h1><%= @event.title %></h1>
    <div class="row">
      <div class="col-lg-12">
        <div class="row">
          <div class="col-md-9">
            <p><%= date_format(@event.start_at) %></p>
            <p>แหล่งข้อมูลอ้างอิง: <%= external_link_to truncate_url(@event.source_url), truncate_url(@event.source_url) %></p>
          </div>
          <div class="col-md-3 share-buttons">
            <ul>
              <li>
                <%= link_to "https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}", target: "_blank", title: "Share on Facebook" do %>
                  <%= icon('facebook') %>
                <% end %>
              </li>
              <li>
                <%= link_to "https://twitter.com/share?url=#{request.original_url}&text=#{@event.title}&via=SafetyAlert.me", target: "_blank", title: "Share on Twitter" do %>
                  <%= icon('twitter') %>
                <% end %>
              </li>
              <li>
                <%= link_to "https://plus.google.com/share?url=#{request.original_url}", target: "_blank", title: "Share on Google Plus" do %>
                  <%= icon('google-plus') %>
                <% end %>
              </li>
              <li>
                <%= link_to "mailto:?subject=#{@event.title}&body=#{request.original_url}", target: "_blank", title: "Share via Email" do %>
                  <%= icon('envelope-o') %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
        <div id="event-map"></div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-9 warning-preparation">
          <h3><strong>เตรียมตัวรับมือภัยพิบัติเบื้องต้น</strong></h3>
          <% if @event.category == "flood" || @event.category == "rainfall" %>
            <%= render partial: "events/flood_preparation" %>
          <% elsif @event.category == "earthquake" %>
            <%= render partial: "events/earthquake_preparation" %>
          <% else %>
            <%= render partial: "events/default_preparation" %>
          <% end %>
        </div>
        <div class="col-md-3 emergency-contact">
          <h3><strong>ขอความช่วยเหลือ พื้นที่ใกล้เคียง</h3></strong>
          <% if @hospitals_nearby.present? %>
            <% @hospitals_nearby.each do |hospital| %>
              <div class="contact-card">
                <div class="card-block">
                  <p class="icon"><%= icon('hospital-o') %></p>
                  <p class="text">
                    <%= external_link_to(hospital.name, "http://www.google.com/search?q=#{hospital.name}") %>
                  </p>
                </div>
                <div class="card-block">
                  <p class="icon"><%= icon('phone') %></p>
                  <p class="text">
                    <%= external_link_to(hospital.tel, "tel:#{hospital.tel}") %>
                  </p>
                </div>
                <div class="card-block">
                  <p class="icon"><%= icon('map-marker') %></p>
                  <p class="text">
                    <%= external_link_to(hospital.address, "http://maps.google.com/?q=#{hospital.address}") %>
                  </p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: { maxZoom: 15 }, internal: {id: 'event-map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": "<%= @event.latitude %>",
        "lng": "<%= @event.longitude %>",
        "picture": {
          "url": "<%= image_path("#{@event.category}.png") %>",
          "width":  32,
          "height": 37
        },
        "infowindow": "<%= @event.title %>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    google.maps.event.trigger(markers[0].getServiceObject(), 'click');
    });
  </script>
<% else %>
  <div class="container">
    <h1>ไม่พบข้อมูล หรือข้อมูลเก่ากว่า 7 วัน</h1>
  </div>
<% end %>