config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  devise_for :users, controllers: {
    registrations: 'user/registrations',
    omniauth_callbacks: 'user/omniauth_callbacks'
  }

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :events, only: [:index, :show]
      resources :locations, only: [:show]
    end
  end
  get "/api/v1/events/category/:category",
    to: "api/v1/events#category", defaults: { format: :json }
  get "/api/v1/events/location/:location",
    to: "api/v1/events#location", defaults: { format: :json }
  get "/api/v1/events/postalcode/:postalcode",
    to: "api/v1/events#postalcode", defaults: { format: :json }

  resources :events , only: [:index, :show]
  get 'pages/about'
  get 'pages/map'
  get 'pages/map_with_location/:location', to: 'pages#map_with_location'
  get 'pages/map_with_category/:category', to: 'pages#map_with_category'
  get '/events/category/:category', to: 'events#category'
  get '/events/location/:location', to: 'events#location'
  get '/events/postalcode/:postalcode', to: 'events#postalcode', as: :events_postalcode
  get '/events/district/:district', to: 'events#district'
  get '/unsubscribes/:token', to: 'unsubscribes#show'

  mount Sidekiq::Web => '/sidekiq'

  get '*unmatched_route', to: 'application#route_not_found'
end

app/views/layouts/_alert.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-6 col-sm-3">
        <h4>SafetyAlert { ME }</h4>
        <ul class="list-unstyled">
          <%= render 'layouts/navigation_links' %>
        </ul>
      </div>
      <div class="col-6 col-sm-3 column">
        <h4>Developer</h4>
        <ul class="list-unstyled">
          <li><%= external_link_to "SafetyAlert API", "http://docs.safetyalert.apiary.io" %></li>
          <li><%= external_link_to "Opensource Project", "https://github.com/wulab/edm-alert" %></li>
        </ul>
      </div>
      <div class="col-12 col-sm-3">
        <!-- TODO: Social Media links -->
      </div>
    </div>
    <br>
    <div class="copyright">
      <%= link_to "SafetyAlert ME", root_path %> ©2017
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav id="top-nav" class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to image_tag("logo_white.png", class: "logo-brand" ) + "SafetyAlert", root_path %>
      </div>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.full_name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "แก้ไขข้อมูล", edit_user_registration_path %></li>
              <li><%= link_to "ข้อมูลเตือนภัยพื้นที่ของคุณ", events_postalcode_path(current_user.location.postal_code) %></li>
              <li><%= link_to "ออกจากระบบ", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "สมัคร", new_user_registration_path, class: "" %></li>
          <li><%= link_to "เข้าสู่ระบบ", new_user_session_path, class: "" %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to "แผนที่", pages_map_path, data: { turbolinks: false } %></li>
<li><%= link_to "ข้อมูลเตือนภัย", events_path %></li>
<li><%= link_to "ทำงานอย่างไร", root_path(anchor: "howitwork") %></li>
<li><%= link_to "เกี่ยวกับเรา", pages_about_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta property="og:image" content="https://cloud.githubusercontent.com/assets/403010/23842817/9e691608-07e9-11e7-9889-afab41a3b4bc.png"/>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= content_for :meta %>

    <title><%= content_for?(:title) ? [ yield(:title),  ' | SafetyAlert ME'].join(' ') : 'SafetyAlert ME' %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kanit:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
    <script src="//maps.google.com/maps/api/js?key=AIzaSyB3qtDLQucaPCgDuqytET0hN7P6LuSLoDA"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div id="main" class="<%= "#{params[:controller].parameterize}-#{params[:action]}" %>">
      <%= render "layouts/alert" %>
      <%= yield %>

      <% unless map_pages? %>
        <%= render 'layouts/footer' %>
      <% end %>
    </div>
  </body>

  <% if current_page?(root_path) %>
    <a id="tars-widget-fab" class="fab bounce closed"
      href="https://safetyalert.hellotars.com/conv/rJtMak" target="_blank"
      style="position:fixed;background-color:#B7E5FF;z-index:2147483647;width:62px;height:62px;cursor:pointer;border-radius:6px;box-shadow:0 2px 6px 0 rgba(0,0,0,.4);overflow:hidden;padding:0;border:0;bottom:4%;right:30px">
      <img class="convbot"
      src="https://cloud.githubusercontent.com/assets/403010/24797484/a86f95ba-1bbb-11e7-8b06-ecaa55a25186.png"
      convbot-color="#FFFFFF"
      style="width:100%">
    </a>
    <script>
      (function(){var js,fs,d=document,id="tars-widget-script",
        b="https://tars-file-upload.s3.amazonaws.com/share/";
        if(!d.getElementById(id)){js=d.createElement("script");
        js.id=id;js.type="text/javascript";
        js.src=b+"js/widget.js";
        fs=d.getElementsByTagName("script")[0];
        fs.parentNode.insertBefore(js,fs)}})();
    </script>
  <% end %>

  <% if map_pages? %>
    <script type="text/javascript">
      handler = Gmaps.build('Google', { markers: { clusterer: undefined  }});
      handler.buildMap({
          provider: {
            disableDefaultUI: true,
            minZoom: 3,
            scaleControl: true,
            zoomControl: true
          },
          internal: {
            id: 'map_canvas'
          }
        },
        function(){
          var json_array = <%=raw @hash.to_json %>
          if (json_array.length > 0) {
            var markers = handler.addMarkers(json_array);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();

            var i = 0;
            setInterval(function () {
              if (i == markers.length) i = 0;
              google.maps.event.trigger(markers[i].getServiceObject(), 'click');
              i++;
            }, 3000);
          }
          else {
            alert("ไม่มีข้อมูลเตือนภัยใน 7 วันที่ผ่านมา");
          }
        }
      );
    </script>
  <% end %>
</html>